#!/bin/bash

# Auto-Build Environment Setup for Complete Profile Editing
# Generated by Planner Agent - Spec 002

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Complete Profile Editing - Spec 002"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# ENVIRONMENT CHECK
# ============================================

echo ""
echo "Checking environment..."
cd /Users/admin/maincomby_bot/miniapp

# Check if .env files exist
if [ ! -f ".env.production" ]; then
    echo -e "${RED}Error: .env.production not found${NC}"
    echo "Please ensure .env.production exists with VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY"
    exit 1
fi

echo -e "${GREEN}Environment files found${NC}"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Checking dependencies..."
if [ ! -d "node_modules" ]; then
    echo "Installing npm dependencies..."
    npm install
else
    echo -e "${GREEN}Dependencies already installed${NC}"
fi

# ============================================
# START FRONTEND DEV SERVER
# ============================================

echo ""
echo "Starting frontend development server..."
npm run dev &
DEV_SERVER_PID=$!

wait_for_service 3000 "Frontend (Vite)"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Database:"
echo "  Supabase URL: https://ndpkxustvcijykzxqxrn.supabase.co"
echo ""
echo "To stop all services:"
echo "  kill $DEV_SERVER_PID"
echo ""
echo "Ready to begin implementation!"
echo "========================================"
