-- MASTER FIX: ALL DATABASE TABLES AND PERMISSIONS
-- Run this in Supabase SQL Editor to resolve 406/401 errors.

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 1. APP SETTINGS & INVITES
-- ==========================================

CREATE TABLE IF NOT EXISTS app_settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    description TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    updated_by BIGINT
);

CREATE TABLE IF NOT EXISTS invites (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    code TEXT NOT NULL UNIQUE,
    inviter_id BIGINT,
    invitee_id BIGINT,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS admin_whitelist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tg_user_id BIGINT NOT NULL UNIQUE,
    added_by BIGINT,
    reason TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 2. EXTENDED PROFILE (COMPANIES, BADGES, LINKS)
-- ==========================================

CREATE TABLE IF NOT EXISTS companies (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    logo_url TEXT,
    website_url TEXT,
    description TEXT,
    industry TEXT,
    is_verified BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_companies (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id BIGINT NOT NULL,
    company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    role TEXT,
    is_primary BOOLEAN DEFAULT true,
    joined_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, company_id)
);

CREATE TABLE IF NOT EXISTS user_links (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id BIGINT NOT NULL,
    link_type TEXT NOT NULL,
    url TEXT NOT NULL,
    title TEXT,
    is_public BOOLEAN DEFAULT true,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, link_type)
);

CREATE TABLE IF NOT EXISTS custom_badges (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    emoji TEXT,
    color TEXT DEFAULT '#c8ff00',
    xp_reward INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_badges (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id BIGINT NOT NULL,
    badge_id UUID NOT NULL REFERENCES custom_badges(id) ON DELETE CASCADE,
    awarded_by BIGINT,
    awarded_reason TEXT,
    awarded_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ,
    is_featured BOOLEAN DEFAULT false,
    UNIQUE(user_id, badge_id)
);

-- ==========================================
-- 3. AVATAR SKINS
-- ==========================================

CREATE TABLE IF NOT EXISTS avatar_skins (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    ring_color TEXT NOT NULL,
    ring_width INTEGER DEFAULT 4,
    ring_offset INTEGER DEFAULT 2,
    glow_enabled BOOLEAN DEFAULT false,
    glow_color TEXT,
    glow_intensity INTEGER,
    css_class TEXT,
    icon_emoji TEXT,
    grant_type TEXT DEFAULT 'manual',
    grant_config JSONB DEFAULT '{}',
    permissions TEXT[] DEFAULT '{}',
    priority INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    is_premium BOOLEAN DEFAULT false,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_avatar_skins (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id BIGINT NOT NULL,
    skin_id UUID NOT NULL REFERENCES avatar_skins(id) ON DELETE CASCADE,
    awarded_by BIGINT,
    awarded_reason TEXT,
    awarded_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ,
    UNIQUE(user_id, skin_id)
);

-- ==========================================
-- 4. BOT CORE TABLES (IF MISSING)
-- ==========================================

CREATE TABLE IF NOT EXISTS bot_users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tg_user_id BIGINT NOT NULL UNIQUE,
    username TEXT,
    first_name TEXT,
    last_name TEXT,
    phone_number TEXT,
    first_seen_at TIMESTAMPTZ DEFAULT NOW(),
    points INTEGER DEFAULT 0,
    warns INTEGER DEFAULT 0,
    banned BOOLEAN DEFAULT false,
    source TEXT,
    invites_remaining INTEGER DEFAULT 5,
    invited_by BIGINT,
    invite_code_used TEXT,
    subscription_tier TEXT DEFAULT 'free',
    subscription_expires_at TIMESTAMPTZ,
    daily_swipes_used INTEGER DEFAULT 0,
    daily_swipes_reset_at TIMESTAMPTZ,
    team_role TEXT,
    active_skin_id UUID
);

CREATE TABLE IF NOT EXISTS bot_profiles (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES bot_users(id) ON DELETE CASCADE,
    bio TEXT,
    occupation TEXT,
    looking_for TEXT,
    can_help_with TEXT,
    needs_help_with TEXT,
    photo_file_id TEXT,
    photo_url TEXT,
    city TEXT DEFAULT 'Минск',
    moderation_status TEXT DEFAULT 'pending',
    is_visible BOOLEAN DEFAULT true,
    skills TEXT[],
    interests TEXT[],
    telegram_username TEXT,
    linkedin_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS bot_swipes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    swiper_id BIGINT NOT NULL REFERENCES bot_users(id) ON DELETE CASCADE,
    swiped_id BIGINT NOT NULL REFERENCES bot_users(id) ON DELETE CASCADE,
    action TEXT NOT NULL,
    swiped_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS bot_matches (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user1_id BIGINT NOT NULL REFERENCES bot_users(id) ON DELETE CASCADE,
    user2_id BIGINT NOT NULL REFERENCES bot_users(id) ON DELETE CASCADE,
    matched_at TIMESTAMPTZ DEFAULT NOW(),
    is_active BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS bot_events (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    description TEXT,
    event_date TIMESTAMPTZ NOT NULL,
    city TEXT DEFAULT 'Минск',
    location TEXT,
    location_url TEXT,
    speakers TEXT,
    max_participants INTEGER,
    registration_deadline TIMESTAMPTZ,
    is_active BOOLEAN DEFAULT true,
    image_url TEXT,
    event_type TEXT DEFAULT 'meetup',
    price INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS bot_registrations (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_id BIGINT NOT NULL REFERENCES bot_events(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES bot_users(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'registered',
    registered_at TIMESTAMPTZ DEFAULT NOW(),
    notes TEXT,
    confirmed BOOLEAN DEFAULT false,
    ticket_code TEXT UNIQUE,
    checked_in_at TIMESTAMPTZ,
    checked_in_by BIGINT
);

-- ==========================================
-- 5. TRANSACTIONS & NOTIFICATIONS
-- ==========================================

CREATE TABLE IF NOT EXISTS xp_transactions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES bot_users(id) ON DELETE CASCADE,
    amount INTEGER NOT NULL,
    reason TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_achievements (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES bot_users(id) ON DELETE CASCADE,
    achievement_id TEXT NOT NULL,
    unlocked_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, achievement_id)
);

CREATE TABLE IF NOT EXISTS app_notifications (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES bot_users(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    data JSONB DEFAULT '{}',
    is_read BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS consultation_requests (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES bot_users(id) ON DELETE CASCADE,
    consultant_tg_id BIGINT NOT NULL,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 6. RPC FUNCTIONS
-- ==========================================

-- 1. Increment points
CREATE OR REPLACE FUNCTION increment_user_points(p_user_id BIGINT, p_points_to_add INTEGER)
RETURNS INTEGER AS $$
DECLARE
    new_points INTEGER;
BEGIN
    UPDATE bot_users
    SET points = COALESCE(points, 0) + p_points_to_add
    WHERE id = p_user_id
    RETURNING points INTO new_points;
    RETURN new_points;
END;
$$ LANGUAGE plpgsql;

-- 2. Generate invite code
CREATE OR REPLACE FUNCTION generate_invite_code()
RETURNS TEXT AS $$
DECLARE
    chars TEXT := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
    result TEXT := '';
    i INTEGER;
BEGIN
    FOR i IN 1..8 LOOP
        result := result || substr(chars, floor(random() * length(chars) + 1)::integer, 1);
    END LOOP;
    RETURN result;
END;
$$ LANGUAGE plpgsql;

-- 3. Create user invites
CREATE OR REPLACE FUNCTION create_user_invites(p_user_id BIGINT, p_count INTEGER DEFAULT 5)
RETURNS INTEGER AS $$
DECLARE
    i INTEGER;
    new_code TEXT;
BEGIN
    FOR i IN 1..p_count LOOP
        LOOP
            new_code := generate_invite_code();
            EXIT WHEN NOT EXISTS (SELECT 1 FROM invites WHERE code = new_code);
        END LOOP;
        INSERT INTO invites (code, inviter_id) VALUES (new_code, p_user_id);
    END LOOP;
    RETURN p_count;
END;
$$ LANGUAGE plpgsql;

-- ==========================================
-- 7. PERMISSIONS & RLS
-- ==========================================

-- Disable RLS on all tables for the beta phase to ensure frontend works
ALTER TABLE bot_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE bot_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE bot_swipes DISABLE ROW LEVEL SECURITY;
ALTER TABLE bot_matches DISABLE ROW LEVEL SECURITY;
ALTER TABLE bot_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE bot_registrations DISABLE ROW LEVEL SECURITY;
ALTER TABLE app_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE invites DISABLE ROW LEVEL SECURITY;
ALTER TABLE admin_whitelist DISABLE ROW LEVEL SECURITY;
ALTER TABLE companies DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_companies DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_links DISABLE ROW LEVEL SECURITY;
ALTER TABLE custom_badges DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_badges DISABLE ROW LEVEL SECURITY;
ALTER TABLE avatar_skins DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_avatar_skins DISABLE ROW LEVEL SECURITY;
ALTER TABLE xp_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_achievements DISABLE ROW LEVEL SECURITY;
ALTER TABLE app_notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE consultation_requests DISABLE ROW LEVEL SECURITY;

-- Ensure public access is allowed if RLS is accidentally re-enabled
DO $$
DECLARE
    t text;
BEGIN
    FOR t IN (SELECT table_name FROM information_schema.tables WHERE table_schema = 'public') LOOP
        EXECUTE format('GRANT ALL ON TABLE %I TO anon, authenticated, service_role;', t);
    END LOOP;
END $$;

-- ==========================================
-- 8. INITIAL DATA
-- ==========================================

INSERT INTO app_settings (key, value, description)
VALUES ('invite_required', 'true', 'Require invite code for access')
ON CONFLICT (key) DO NOTHING;

INSERT INTO custom_badges (slug, name, description, emoji, color)
VALUES ('core_team', 'Core Team', 'MAIN Community core team member', '⭐', '#c8ff00')
ON CONFLICT (slug) DO NOTHING;
