#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 003: Unit Test Foundation

set -e

echo "========================================"
echo "Unit Test Foundation - Dev Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# PRE-FLIGHT CHECKS
# ============================================

echo ""
echo "Running pre-flight checks..."

# Check if node is installed
if ! command -v node &> /dev/null; then
    echo -e "${RED}Error: Node.js is not installed${NC}"
    exit 1
fi

# Check if npm is installed
if ! command -v npm &> /dev/null; then
    echo -e "${RED}Error: npm is not installed${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Node.js $(node --version)${NC}"
echo -e "${GREEN}✓ npm $(npm --version)${NC}"

# ============================================
# INSTALL DEPENDENCIES (if needed)
# ============================================

if [ ! -d "node_modules" ]; then
    echo ""
    echo "Installing dependencies..."
    npm install
fi

# ============================================
# START DEVELOPMENT SERVER
# ============================================

echo ""
echo "Starting development server..."
echo ""

# Start Vite dev server
npm run dev &
DEV_PID=$!

# Wait for dev server to be ready
wait_for_service 5173 "Vite Dev Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:5173"
echo ""
echo "Test Commands:"
echo "  npm run test           - Run tests in watch mode"
echo "  npm run test:coverage  - Generate coverage report"
echo "  npm run test:ui        - Open Vitest UI"
echo ""
echo "To stop the server, press Ctrl+C"
echo ""

# Wait for Ctrl+C
trap "echo ''; echo 'Shutting down...'; kill $DEV_PID 2>/dev/null; exit 0" INT
wait $DEV_PID
